var times = [
    "AMÉRICA-MG", "ATHLETICO-PR", "ATLÉTICO-GO", "ATLÉTICO-MG", "BAHIA", "BRAGANTINO", "CEARÁ", "CHAPECOENSE", "CORINTHIANS", "CUIABÁ", "FLAMENGO", "FLUMINENSE", "FORTALEZA", "GRÊMIO", "INTERNACIONAL", "JUVENTUDE", "PALMEIRAS", "SANTOS", "SÃO PAULO", "SPORT", "BOTAFOGO-SERIE B", "CRUZEIRO-SERIE B", "VASCO-SERIE B", "ARSENAL-EUROPA", "BARCELONA-EUROPA", "BAYERN-EUROPA", "PSG-EUROPA","REAL MADRID-EUROPA", "JUVENTUS-EUROPA" 
  ]
  
  var sites = [
    "https://www.americamineiro.com.br/", "https://www.athletico.com.br/", "https://atleticogoianiense.com.br/", "https://atletico.com.br/", "https://www.esporteclubebahia.com.br/", "https://www.redbullbragantino.com.br/", "https://cearasc.com/", "https://chapecoense.com/pt", "https://www.corinthians.com.br/", "http://cuiabaesporteclube.com.br/", "https://www.flamengo.com.br/", "https://www.fluminense.com.br/", "https://fortaleza1918.com.br/", "https://gremio.net/", "https://internacional.com.br/", "https://www.juventude.com.br/", "https://www.palmeiras.com.br/pt-br/", "https://www.santosfc.com.br/", "http://www.saopaulofc.net/", "https://sportrecife.com.br/", "https://www.botafogo.com.br/", "https://www.cruzeiro.com.br/", "https://vasco.com.br/", "https://www.arsenal.com/", "https://www.fcbarcelona.com/en/", "https://fcbayern.com/en", "https://pt.psg.fr/", "https://www.realmadrid.com/pt", "https://www.juventus.com/pt/"
  ]
  
  var imagem = [
    "https://s.glbimg.com/es/sde/f/organizacoes/2019/02/28/America-MG-VERDE-fev2019-01.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2019/09/09/Athletico-PR.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2020/07/02/atletico-go-2020.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/10/atletico-mg.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/bahia.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2019/12/30/svg.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2019/10/10/ceara.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/chapecoense.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2019/09/30/Corinthians.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/12/26/Cuiaba_EC.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/04/10/Flamengo-2018.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/fluminense.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/06/10/optimised.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/12/gremio.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/internacional.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/juventude.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2019/07/06/Palmeiras.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/12/santos.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/sao-paulo.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/sport.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2019/02/04/botafogo-svg.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2021/02/13/cruzeiro_2021.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/vasco.svg", "https://s.glbimg.com/es/sde/f/equipes/2018/03/11/arsenal.svg", "https://s.glbimg.com/es/sde/f/equipes/2018/03/11/barcelona.svg", "https://s.glbimg.com/es/sde/f/organizacoes/2018/03/11/bayern-de-munique.svg", "https://s.glbimg.com/es/sde/f/equipes/2018/03/12/paris-saint-germain.svg", "https://s.glbimg.com/es/sde/f/equipes/2018/03/12/real-madrid.svg", "https://s.glbimg.com/es/sde/f/equipes/2018/03/11/juventus.svg"
  ]
  
  for (let i = 0; i < times.length; i++) {
    document.write(`<a class="time" href="${sites[i]}" target="_blank"><img src="${imagem[i]}" /><h3 class="clube">`, times[i] ,'</h3></a>' );
  }
  